version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: .
            dockerfile: MicroserviceConfigServer/Dockerfile-configserver
        image: config-server:latest    
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - emp-network
        volumes:
            - config-repo:/var/lib/config-repo
            
    eureka-server:
        container_name: eureka-server
        build:
            context: .
            dockerfile: EurekaNetflixRegistryServer/Dockerfile
        image: eureka-server:latest
        expose:
            - 9091
        ports:
            - 9091:9091
        networks:
            - emp-network
    EmployeeSearchService:
        container_name: EmployeeSearch
        build:
            context: .
            dockerfile: MicroServiceClient/Dockerfile
        image: employeesearch:latest
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:9090"}}}},{"eureka": {"client": {"serviceUrl": {"defaultZone": "http://eureka-server:9091/eureka"}}}}'
        expose:
            - 8080
        ports:
            - 8080:8080
        networks:
            - emp-network
        links:
            - config-server:config-server
            - eureka-server:eureka-server
        depends_on:
            - config-server
            - eureka-server
        logging:
            driver: json-file          
volumes:
    config-repo:
        external: true 
networks:
    emp-network:
        driver: bridge
           