FROM alpine-jdk:base
MAINTAINER javaonfly
COPY /build/libs/MicroserviceConfigServer*.jar /opt/lib/MicroserviceConfigServer.jar
RUN mkdir /var/lib/config-repo
COPY config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/MicroserviceConfigServer.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090
